[programs.devnet]
myepicproject = "DZZ44qtqbbUQQ6DHGRoVjTurKWfApr93jCcTJPkKvCCM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/rafael/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
